In [2]:
!pip uninstall -y transformers && pip install git+https://github.com/huggingface/transformers

Found existing installation: transformers 4.41.0.dev0
Uninstalling transformers-4.41.0.dev0:
  Successfully uninstalled transformers-4.41.0.dev0
Collecting git+https://github.com/huggingface/transformers
  Cloning https://github.com/huggingface/transformers to /tmp/pip-req-build-1xh2t_xl
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/transformers /tmp/pip-req-build-1xh2t_xl
  Resolved https://github.com/huggingface/transformers to commit 4208c428f6a42e6f58ab44014e696bdf49def855
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers==4.41.0.dev0) (3.14.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.41.0.dev0) (0.23.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.41.0.dev0) (1.25.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers==4.41.0.dev0) (24.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.41.0.dev0) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers==4.41.0.dev0) (2023.12.25)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers==4.41.0.dev0) (2.31.0)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers==4.41.0.dev0) (0.19.1)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers==4.41.0.dev0) (0.4.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers==4.41.0.dev0) (4.66.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.0->transformers==4.41.0.dev0) (2023.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.0->transformers==4.41.0.dev0) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.41.0.dev0) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.41.0.dev0) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.41.0.dev0) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers==4.41.0.dev0) (2024.2.2)
Building wheels for collected packages: transformers
  Building wheel for transformers (pyproject.toml) ... done
  Created wheel for transformers: filename=transformers-4.41.0.dev0-py3-none-any.whl size=9050431 sha256=e25b36bff2e6ea676796ff52d4fae78493ee7715ec7dd58b20e970f5fe663f23
  Stored in directory: /tmp/pip-ephem-wheel-cache-mta2l4u7/wheels/c0/14/d6/6c9a5582d2ac191ec0a483be151a4495fe1eb2a6706ca49f1b
Successfully built transformers
Installing collected packages: transformers
Successfully installed transformers-4.41.0.dev0

In [3]:
from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained("microsoft/Phi-3-mini-128k-instruct", attn_implementation="eager")
tokenizer = AutoTokenizer.from_pretrained("microsoft/Phi-3-mini-128k-instruct")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/3.35k [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/16.3k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.67G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/172 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/3.17k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/568 [00:00<?, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

In [4]:
from google.colab import drive
import pandas as pd

drive.mount('/content/drive')
%cd 'drive/MyDrive/Projects/Dastpokht/comment_analyzer'

Mounted at /content/drive
/content/drive/MyDrive/Projects/Dastpokht/comment_analyzer

In [5]:
df = pd.read_csv("./samples.csv", encoding='utf-8').drop(['Unnamed: 0'],axis=1)
df

,comment_text,order,ingredients,foods,services,qualities
0,افتضاح تا بحال به عمرم پیتزا به این بدی ندیده ...,['پیتزا سیر و استیک ایتالیایی یک نفره (25 سانت...,{'پیتزا سیر و استیک ایتالیایی یک نفره (25 سانت...,"{""{\""product_id\"": 22922785, \""product_title\""...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""food_rate\"": \""0\"", \""food_title\"": \""پیت..."
1,اصلا طعم قرمه سبزی نداشت یعنی اگر خودم سفارش ن...,"['چلو خورشت قورمه سبزی', 'نوشابه شیشه ای کوکا ...",{'چلو خورشت قورمه سبزی': '200 گرم خورشت٬ 70 گر...,"{""{\""product_id\"": 6391220, \""product_title\"":...",{},"{""{\""food_rate\"": \""1\"", \""food_title\"": \""چلو..."
2,چلوکباب سماغ نداشت,['چلو کباب\u200c کوبیده مخصوص اقتصادی'],{'چلو کباب\u200c کوبیده مخصوص اقتصادی': 'یک سی...,"{""{\""product_id\"": 23638165, \""product_title\""...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""food_rate\"": \""0\"", \""food_title\"": \""چلو..."
3,حتما دوبار سفارش می دم,['زرشک پلو با مرغ سس پز ران'],{'زرشک پلو با مرغ سس پز ران': 'یک تکه مرغ سس پ...,"{""{\""product_id\"": 5545444, \""product_title\"":...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""ز..."
4,عالی,['خوراک جوجه کباب ترش گیلانه'],{'خوراک جوجه کباب ترش گیلانه': 'یک سیخ جوجه کب...,"{""{\""product_id\"": 20430113, \""product_title\""...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""food_rate\"": \""5\"", \""food_title\"": \""خور..."
...,...,...,...,...,...,...
95,طعم برگر بشدت بد و بی مزه بود سیب زمینی های مخ...,"['همبرگر معمولی', 'ساندویچ هندی', 'نوشابه خانو...",{'همبرگر معمولی': 'برگر شرکتی 30%، کاهو، گوجه،...,"{""{\""product_id\"": 6256725, \""product_title\"":...","{""{\""service_rate\"": \""0\"", \""part_of_comment\...","{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""ن..."
96,فلفل کبابی نداشت و نونش کم بود نسبت به ۴ سیخی ...,['خوراک کباب کوبیده یک سیخ'],{'خوراک کباب کوبیده یک سیخ': 'کباب کوبیده گوشت...,"{""{\""product_id\"": 21436811, \""product_title\""...","{""{\""service_rate\"": \""2\"", \""part_of_comment\...","{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""خ..."
97,حجم مواد خوب بود و مزه خوبی داشت نسبتا ولی پیت...,"['س️اندویچ ژامبون تنوری مخصوص ویولا', 'پیتزا ک...",{'س️اندویچ ژامبون تنوری مخصوص ویولا': '200 گرم...,"{""{\""product_id\"": 24755883, \""product_title\""...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""س..."
98,عالی,['چلو خورشت قورمه سبزی'],{'چلو خورشت قورمه سبزی': 'یک پرس خورشت قورمه س...,"{""{\""product_id\"": 7588082, \""product_title\"":...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""food_rate\"": \""5\"", \""food_title\"": \""چلو..."
99,پول پیک پانزده هزار تومن نمیرزه,['ساندویچ هات بیتس'],{'ساندویچ هات بیتس': '2 عدد ساندویچ مینی ھات د...,"{""{\""product_id\"": 19131318, \""product_title\""...","{""{\""service_rate\"": \""1\"", \""part_of_comment\...","{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""س..."

In [6]:
prompt_enhancements = """Suppose that we are working in the domain of a food delivery app.
Here is the list of foods and beverages ordered by a user, let's call it 'UserOrder':
UserOrder: {order}

After receiving the 'UserOrder', here is the user's comment (review) about their experience having UserOrder (called 'UserComment'):
UserComment: {comment}
As you see, UserComment expresses the user's satisfaction with the food quality and services delivered.

If available, here is the list of ingredients per each food included in the UserOrder (called 'FoodIngredients'):
FoodIngredients: {ingredients}

Having the context provided, your task is to evaluate the food quality and services delivered based on UserComment. In other words, you should assign a score per each food and services delivered. Let's think step by step:
First, inspect the UserComment precisely.

Then, Based on UserComment, assign a score per each of the foods ordered (an integer between 0 and 5). In other words, all the food titles mentioned in the UserOrder must get a score field. If UserComment does not include any specific review for any of the food ordered, set the corresponding food score to 'Nan'.
*ATTENTION*: In this step, if UserComment is a general positive or negative comment and does not specify any particular food item, apply it to all food items ordered.
For example: Having UserComment='همه چی عالی', all the food items ordered will get a 5 score.

For the next step, refer to UserComment again. Based on UserComment, assign a score per each service provided (if any). To achieve this, first, you need to specify the relevant part of the UserComment expressing the user's experience with the service. Then, classify that service into one of these categories:
'[Delivery time, Quality of packaging, Cost of packaging, Cost per value of foods, Overall quality, Staff behavior, Food temperature, Delivered food not as ordered]'
After that, assign a score (an integer between 0 and 5) to that service based on part_of_comment. Feel free to set the service score as 'Nan' if the user seems unclear about the satisfaction with the service provided.

*ATTENTION*: As you see, the UserComment is in Persian. Thus, be mindful of any different Persian idioms or slang used and their actual meanings.

Finally, Based on the information inferred in the previous steps, generate JSON about the foods and services in this format:
```
{{
    qualities: [
        {{
            food_title: <food_title>,
            food_rate: <food_rate>
        }}
    ],
    services: [
        {{
            part_of_comment: <part_of_comment>,
            service_rate: <service_rate>,
            service_classified: <service_classified>
        }}
    ]
}}
```
Output only the JSON. Do not output any extra information or explanations.

"""

system_role = "You are a helpful digital assisstant having brilliant analytical skills."

In [15]:
result = pd.read_csv("./batch_1_result.csv", encoding='utf-8')

In [ ]:
# result = df[['comment_text', 'order']].copy()

In [16]:
result.iloc[60:]

,comment_text,order,response
60,عالی بود,['رویال برگر ذغالی'],"```json\n\n{\n ""qualities"": [\n {\n ..."
61,خوب بود,['چلو جوجه کباب سینه'],"```json\n\n{\n ""qualities"": [\n {\n ..."
62,خوشمزه ترین پاستایی بود که تا الان خوردم\nممنو...,['پاستا پنه'],"```json\n\n{\n ""qualities"": [\n {\n ..."
63,چرب بود به شدت کباب و کیفیتش پایین بود…,['چلو کباب لقمه'],"```json\n\n{\n ""qualities"": [\n {\n ..."
64,فقط مثل همیشه سس سفید همراهش نبود توی جعبه پیت...,"['نوشابه قوطی سون آپ', 'پیتزا آمریکایی لاکچری ...","```json\n\n{\n ""qualities"": [\n {\n ..."
65,چرا باید عکس سوپ جو سوپ شیر باشه که ادم اشتباه...,['سوپ جو (یک کیلو)'],"```json\n\n{\n ""qualities"": [\n {\n ..."
66,یک ماست و خیار اشتباها ارسال شده بود چطور میتو...,"['چلو خورشت قورمه سبزی', 'دسر تیرامیسو شکلاتی'...","```json\n\n{\n ""qualities"": [\n {\n ..."
67,عالی,['پاستا پنه اربیتا میگو'],"```json\n\n{\n ""qualities"": [\n {\n ..."
68,ترشی کلم رو نزنید.,"['شات سس قارچ', 'سالاد کلم', 'ساندویچ چیکن دونر']","```json\n\n{\n ""qualities"": [\n {\n ..."
69,عالی بود,['ته چین مرغ و بادمجان سینه'],"```json\n\n{\n ""qualities"": [\n {\n ..."
70,ضعیف زیاد,"['نوشابه خانواده کوکا کولا', 'پیتزا پپرونی']","```json\n\n{\n ""qualities"": [\n {\n ..."
71,حسابی سیر و پیاز داغ و سبزی داشت,['آش رشته (ظرف بزرگ)'],"```json\n\n{\n ""qualities"": [\n {\n ..."
72,افتشاحتر از این نمیشد... گوشت برگر بو می داد.....,"['اسموکی چیز برگر', 'موزارلا چیز رول']","```json\n\n{\n ""qualities"": [\n {\n ..."
73,عالی,['چلو خورشت قورمه سبزی'],"```json\n\n{\n ""qualities"": [\n {\n ..."
74,کیفیت اجناس خوب بود اما برای بسته بندی و ارسال...,"['لیمو شیرین درجه 1 1 کیلوگرم ± 50 گرم', 'شلغم...","```json\n\n{\n ""qualities"": [\n {""fo..."
75,عالییییییی بود,['چلو خورشت فسنجان مرغ'],"```json\n\n{\n ""qualities"": [\n {\n ..."
76,کیفیت غذا و تازه بودن ماهی عاااالی، بسته بندی ...,['چلو ماهی قزل آلا کبابی'],"```json\n\n{\n ""qualities"": [\n {\n ..."
77,عالی,"['سالاد فصل', 'چلو ساده', 'خوراک بره کباب']","```json\n\n{\n ""qualities"": [\n {\n ..."
78,هم ظرف کوچیک بود هم برنج کم بود,"['چلو کباب وزیری', 'نوشابه بطری پپسی']","```json\n\n{\n ""qualities"": [\n {\n ..."
79,مثل همیشه عالی خیلی از کیفیت خوب پیتزاتون ممنونم,"['نوشابه قوطی کوکاکولا', 'نوشابه قوطی زیرو',...","```json\n\n{\n ""qualities"": [\n {""fo..."
80,ممنون بابت کیفیت خوب و تحویل تمیز سفارش.,"['کامل', 'ران مرغ 1 کیلوگرم', 'بدون پوست']","```json\n\n{\n ""qualities"": [\n {\n ..."
81,فست فود قدیمی جردن بسیار خوب خوشمزه متریال تازه,"['ساندویچ هات داگ ساده', 'سیب زمینی سرخ شده',...","```json\n\n{\n ""qualities"": [\n {\n ..."
82,خوبه.,['ساندویچ ژامبون لیونر سردویچ دو نفره'],"```json\n\n{\n ""qualities"": [\n {\n ..."
83,طعم کلی خوب بود و راضی بودم. داخل سوسیس یه تکه...,['ساندویچ مخصوص کوکتل آرژانتینی کوچک'],"```json\n\n{\n ""qualities"": [\n {\n ..."
84,الوچه ها همه خراب بودن بنظرم باید از چرخه فروش...,"['آلوچه ریز 500 گرم', 'مغز گردو ایرانی معمولی ...","```json\n\n{\n ""qualities"": [\n {""fo..."
85,غذا سرد,['باقالی پلو با گوشت'],"```json\n\n{\n ""qualities"": [\n {\n ..."
86,خوب بود ممنون,"['نوشابه بطری فانتا پرتقالی', 'کباب کوبیده یک ...","```json\n\n{\n ""qualities"": [\n {\n ..."
87,استرامبولی های فایر در عین کیفیت از استرامبولی...,"['نوشابه خانواده کوکا کولا', 'سالاد کلم', 'است...","```json\n\n{\n ""qualities"": [\n {\n ..."
88,خوب بود,"['پیتزا میکس رویال', 'سیب زمینی سرخ کرده']","```json\n\n{\n ""qualities"": [\n {\n ..."
89,فلافل عالی ولی بندری معمولی. خیلی خورد شده بود...,['ساندویچ بندری بندری'],"```json\n\n{\n ""qualities"": [\n {\n ..."
90,غذا خوب بود \nمهمتر از همه این بود که چون من گ...,['چلو کباب وزیری'],"```json\n\n{\n ""qualities"": [\n {\n ..."
91,به نظر شیرین پلو و مرغ خوب نبود و مواد تشکیل د...,['چلو خورشت قیمه نثار مخصوص'],NaN
92,ممنونم مثلا همیشه عالی وخوب با کیفیت,"['پسته فندقی شور نیم کیلوگرم', 'آجیل چهارشنبه ...",NaN
93,من مشتری ثابت و قدیمی بودم! و به همین راحتی دی...,"['نوشابه خانواده پپسی', 'ساندویچ پیتزا']",NaN
94,ممنونم از فروشگاه شما بابت فعالیت در اسنپ,"['شنیسل فیله مرغ 1 کیلوگرم', 'کامل']",NaN
95,طعم برگر بشدت بد و بی مزه بود سیب زمینی های مخ...,"['همبرگر معمولی', 'ساندویچ هندی', 'نوشابه خانو...",NaN
96,فلفل کبابی نداشت و نونش کم بود نسبت به ۴ سیخی ...,['خوراک کباب کوبیده یک سیخ'],NaN
97,حجم مواد خوب بود و مزه خوبی داشت نسبتا ولی پیت...,"['س️اندویچ ژامبون تنوری مخصوص ویولا', 'پیتزا ک...",NaN
98,عالی,['چلو خورشت قورمه سبزی'],NaN
99,پول پیک پانزده هزار تومن نمیرزه,['ساندویچ هات بیتس'],NaN

In [ ]:
result["response"] = ""
result

,comment_text,order,response
0,افتضاح تا بحال به عمرم پیتزا به این بدی ندیده ...,['پیتزا سیر و استیک ایتالیایی یک نفره (25 سانت...,
1,اصلا طعم قرمه سبزی نداشت یعنی اگر خودم سفارش ن...,"['چلو خورشت قورمه سبزی', 'نوشابه شیشه ای کوکا ...",
2,چلوکباب سماغ نداشت,['چلو کباب\u200c کوبیده مخصوص اقتصادی'],
3,حتما دوبار سفارش می دم,['زرشک پلو با مرغ سس پز ران'],
4,عالی,['خوراک جوجه کباب ترش گیلانه'],
...,...,...,...
95,طعم برگر بشدت بد و بی مزه بود سیب زمینی های مخ...,"['همبرگر معمولی', 'ساندویچ هندی', 'نوشابه خانو...",
96,فلفل کبابی نداشت و نونش کم بود نسبت به ۴ سیخی ...,['خوراک کباب کوبیده یک سیخ'],
97,حجم مواد خوب بود و مزه خوبی داشت نسبتا ولی پیت...,"['س️اندویچ ژامبون تنوری مخصوص ویولا', 'پیتزا ک...",
98,عالی,['چلو خورشت قورمه سبزی'],
99,پول پیک پانزده هزار تومن نمیرزه,['ساندویچ هات بیتس'],

In [17]:
for index, row in df.iloc[91:].iterrows():
    prompt = prompt_enhancements.format(order=row['order'], comment=row['comment_text'], ingredients=row['ingredients'])
    messages = [{"role": "system",
            "content": f"{system_role}"},
    {"role": "user",
    "content": f"{prompt}"}]


    inputs = tokenizer.apply_chat_template(messages, add_generation_prompt=True, return_tensors="pt")

    outputs = model.generate(inputs, max_new_tokens=2000, temperature=0.0)
    text = tokenizer.batch_decode(outputs[:, inputs.shape[1]:])[0]
    result.loc[index, "response"] = text
    print(f"{index} Done.")

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:485: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(

91 Done.
92 Done.
93 Done.
94 Done.
95 Done.
96 Done.
97 Done.
98 Done.
99 Done.

In [18]:
result

,comment_text,order,response
0,افتضاح تا بحال به عمرم پیتزا به این بدی ندیده ...,['پیتزا سیر و استیک ایتالیایی یک نفره (25 سانت...,"```json\n\n{\n ""qualities"": [\n {\n ..."
1,اصلا طعم قرمه سبزی نداشت یعنی اگر خودم سفارش ن...,"['چلو خورشت قورمه سبزی', 'نوشابه شیشه ای کوکا ...","```json\n\n{\n ""qualities"": [\n {\n ..."
2,چلوکباب سماغ نداشت,['چلو کباب\u200c کوبیده مخصوص اقتصادی'],"```json\n\n{\n ""qualities"": [\n {\n ..."
3,حتما دوبار سفارش می دم,['زرشک پلو با مرغ سس پز ران'],"```json\n\n{\n ""qualities"": [\n {\n ..."
4,عالی,['خوراک جوجه کباب ترش گیلانه'],"```json\n\n{\n ""qualities"": [\n {\n ..."
...,...,...,...
95,طعم برگر بشدت بد و بی مزه بود سیب زمینی های مخ...,"['همبرگر معمولی', 'ساندویچ هندی', 'نوشابه خانو...","```json\n\n{\n ""qualities"": [\n {\n ..."
96,فلفل کبابی نداشت و نونش کم بود نسبت به ۴ سیخی ...,['خوراک کباب کوبیده یک سیخ'],"```json\n\n{\n ""qualities"": [\n {\n ..."
97,حجم مواد خوب بود و مزه خوبی داشت نسبتا ولی پیت...,"['س️اندویچ ژامبون تنوری مخصوص ویولا', 'پیتزا ک...","```json\n\n{\n ""qualities"": [\n {\n ..."
98,عالی,['چلو خورشت قورمه سبزی'],"```json\n\n{\n ""qualities"": [\n {\n ..."
99,پول پیک پانزده هزار تومن نمیرزه,['ساندویچ هات بیتس'],"```json\n\n{\n ""qualities"": [\n {\n ..."

In [19]:
result.iloc[59:]

,comment_text,order,response
59,همه چی عالی فقط سرد بود,"['پیتزا مرغ و قارچ آمریکایی 24 سانتی متری', 'ر...","```json\n\n{\n ""qualities"": [\n {\n ..."
60,عالی بود,['رویال برگر ذغالی'],"```json\n\n{\n ""qualities"": [\n {\n ..."
61,خوب بود,['چلو جوجه کباب سینه'],"```json\n\n{\n ""qualities"": [\n {\n ..."
62,خوشمزه ترین پاستایی بود که تا الان خوردم\nممنو...,['پاستا پنه'],"```json\n\n{\n ""qualities"": [\n {\n ..."
63,چرب بود به شدت کباب و کیفیتش پایین بود…,['چلو کباب لقمه'],"```json\n\n{\n ""qualities"": [\n {\n ..."
64,فقط مثل همیشه سس سفید همراهش نبود توی جعبه پیت...,"['نوشابه قوطی سون آپ', 'پیتزا آمریکایی لاکچری ...","```json\n\n{\n ""qualities"": [\n {\n ..."
65,چرا باید عکس سوپ جو سوپ شیر باشه که ادم اشتباه...,['سوپ جو (یک کیلو)'],"```json\n\n{\n ""qualities"": [\n {\n ..."
66,یک ماست و خیار اشتباها ارسال شده بود چطور میتو...,"['چلو خورشت قورمه سبزی', 'دسر تیرامیسو شکلاتی'...","```json\n\n{\n ""qualities"": [\n {\n ..."
67,عالی,['پاستا پنه اربیتا میگو'],"```json\n\n{\n ""qualities"": [\n {\n ..."
68,ترشی کلم رو نزنید.,"['شات سس قارچ', 'سالاد کلم', 'ساندویچ چیکن دونر']","```json\n\n{\n ""qualities"": [\n {\n ..."
69,عالی بود,['ته چین مرغ و بادمجان سینه'],"```json\n\n{\n ""qualities"": [\n {\n ..."
70,ضعیف زیاد,"['نوشابه خانواده کوکا کولا', 'پیتزا پپرونی']","```json\n\n{\n ""qualities"": [\n {\n ..."
71,حسابی سیر و پیاز داغ و سبزی داشت,['آش رشته (ظرف بزرگ)'],"```json\n\n{\n ""qualities"": [\n {\n ..."
72,افتشاحتر از این نمیشد... گوشت برگر بو می داد.....,"['اسموکی چیز برگر', 'موزارلا چیز رول']","```json\n\n{\n ""qualities"": [\n {\n ..."
73,عالی,['چلو خورشت قورمه سبزی'],"```json\n\n{\n ""qualities"": [\n {\n ..."
74,کیفیت اجناس خوب بود اما برای بسته بندی و ارسال...,"['لیمو شیرین درجه 1 1 کیلوگرم ± 50 گرم', 'شلغم...","```json\n\n{\n ""qualities"": [\n {""fo..."
75,عالییییییی بود,['چلو خورشت فسنجان مرغ'],"```json\n\n{\n ""qualities"": [\n {\n ..."
76,کیفیت غذا و تازه بودن ماهی عاااالی، بسته بندی ...,['چلو ماهی قزل آلا کبابی'],"```json\n\n{\n ""qualities"": [\n {\n ..."
77,عالی,"['سالاد فصل', 'چلو ساده', 'خوراک بره کباب']","```json\n\n{\n ""qualities"": [\n {\n ..."
78,هم ظرف کوچیک بود هم برنج کم بود,"['چلو کباب وزیری', 'نوشابه بطری پپسی']","```json\n\n{\n ""qualities"": [\n {\n ..."
79,مثل همیشه عالی خیلی از کیفیت خوب پیتزاتون ممنونم,"['نوشابه قوطی کوکاکولا', 'نوشابه قوطی زیرو',...","```json\n\n{\n ""qualities"": [\n {""fo..."
80,ممنون بابت کیفیت خوب و تحویل تمیز سفارش.,"['کامل', 'ران مرغ 1 کیلوگرم', 'بدون پوست']","```json\n\n{\n ""qualities"": [\n {\n ..."
81,فست فود قدیمی جردن بسیار خوب خوشمزه متریال تازه,"['ساندویچ هات داگ ساده', 'سیب زمینی سرخ شده',...","```json\n\n{\n ""qualities"": [\n {\n ..."
82,خوبه.,['ساندویچ ژامبون لیونر سردویچ دو نفره'],"```json\n\n{\n ""qualities"": [\n {\n ..."
83,طعم کلی خوب بود و راضی بودم. داخل سوسیس یه تکه...,['ساندویچ مخصوص کوکتل آرژانتینی کوچک'],"```json\n\n{\n ""qualities"": [\n {\n ..."
84,الوچه ها همه خراب بودن بنظرم باید از چرخه فروش...,"['آلوچه ریز 500 گرم', 'مغز گردو ایرانی معمولی ...","```json\n\n{\n ""qualities"": [\n {""fo..."
85,غذا سرد,['باقالی پلو با گوشت'],"```json\n\n{\n ""qualities"": [\n {\n ..."
86,خوب بود ممنون,"['نوشابه بطری فانتا پرتقالی', 'کباب کوبیده یک ...","```json\n\n{\n ""qualities"": [\n {\n ..."
87,استرامبولی های فایر در عین کیفیت از استرامبولی...,"['نوشابه خانواده کوکا کولا', 'سالاد کلم', 'است...","```json\n\n{\n ""qualities"": [\n {\n ..."
88,خوب بود,"['پیتزا میکس رویال', 'سیب زمینی سرخ کرده']","```json\n\n{\n ""qualities"": [\n {\n ..."
89,فلافل عالی ولی بندری معمولی. خیلی خورد شده بود...,['ساندویچ بندری بندری'],"```json\n\n{\n ""qualities"": [\n {\n ..."
90,غذا خوب بود \nمهمتر از همه این بود که چون من گ...,['چلو کباب وزیری'],"```json\n\n{\n ""qualities"": [\n {\n ..."
91,به نظر شیرین پلو و مرغ خوب نبود و مواد تشکیل د...,['چلو خورشت قیمه نثار مخصوص'],"```json\n\n{\n ""qualities"": [\n {\n ..."
92,ممنونم مثلا همیشه عالی وخوب با کیفیت,"['پسته فندقی شور نیم کیلوگرم', 'آجیل چهارشنبه ...","```json\n\n{\n ""qualities"": [\n {\n ..."
93,من مشتری ثابت و قدیمی بودم! و به همین راحتی دی...,"['نوشابه خانواده پپسی', 'ساندویچ پیتزا']","```json\n\n{\n ""qualities"": [\n {\n ..."
94,ممنونم از فروشگاه شما بابت فعالیت در اسنپ,"['شنیسل فیله مرغ 1 کیلوگرم', 'کامل']","```json\n\n{\n ""qualities"": [\n {\n ..."
95,طعم برگر بشدت بد و بی مزه بود سیب زمینی های مخ...,"['همبرگر معمولی', 'ساندویچ هندی', 'نوشابه خانو...","```json\n\n{\n ""qualities"": [\n {\n ..."
96,فلفل کبابی نداشت و نونش کم بود نسبت به ۴ سیخی ...,['خوراک کباب کوبیده یک سیخ'],"```json\n\n{\n ""qualities"": [\n {\n ..."
97,حجم مواد خوب بود و مزه خوبی داشت نسبتا ولی پیت...,"['س️اندویچ ژامبون تنوری مخصوص ویولا', 'پیتزا ک...","```json\n\n{\n ""qualities"": [\n {\n ..."
98,عالی,['چلو خورشت قورمه سبزی'],"```json\n\n{\n ""qualities"": [\n {\n ..."
99,پول پیک پانزده هزار تومن نمیرزه,['ساندویچ هات بیتس'],"```json\n\n{\n ""qualities"": [\n {\n ..."

In [ ]:
for index, row in df.iterrows():
    prompt = prompt_enhancements.format(order=row['order'], comment=row['comment_text'], ingredients=row['ingredients'])
    messages = [{"role": "system",
            "content": f"{system_role}"},
    {"role": "user",
    "content": f"{prompt}"}]


    inputs = tokenizer.apply_chat_template(messages, add_generation_prompt=True, return_tensors="pt")

    outputs = model.generate(inputs, max_new_tokens=2000, temperature=0.0)
    text = tokenizer.batch_decode(outputs[:, inputs.shape[1]:])[0]
    result.loc[index, "response"] = text
    print(f"{index} Done.")

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:485: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(

0 Done.
1 Done.
2 Done.
3 Done.
4 Done.
5 Done.
6 Done.
7 Done.
8 Done.
9 Done.
10 Done.
11 Done.
12 Done.
13 Done.
14 Done.
15 Done.
16 Done.
17 Done.
18 Done.
19 Done.
20 Done.
21 Done.
22 Done.
23 Done.
24 Done.
25 Done.
26 Done.
27 Done.
28 Done.
29 Done.
30 Done.
31 Done.
33 Done.
34 Done.
35 Done.
36 Done.
37 Done.
38 Done.
39 Done.
40 Done.
41 Done.
42 Done.
43 Done.
44 Done.
45 Done.
46 Done.
47 Done.
48 Done.
49 Done.
50 Done.
51 Done.
52 Done.
53 Done.
54 Done.
55 Done.
56 Done.
57 Done.
58 Done.
59 Done.

KeyboardInterrupt:

In [20]:
result.to_csv('./batch_1_result.csv', index=False)

In [ ]:
with open('./samples_output.txt', 'w', encoding='utf-8') as f:
    for index, row in df.iterrows():
        prompt = prompt_enhancements.format(order=row['order'], comment=row['comment_text'], ingredients=row['ingredients'])
        messages = [{"role": "system",
                "content": f"{system_role}"},
        {"role": "user",
        "content": f"{prompt}"}]


        inputs = tokenizer.apply_chat_template(messages, add_generation_prompt=True, return_tensors="pt")

        outputs = model.generate(inputs, max_new_tokens=2000, temperature=0.0)
        text = tokenizer.batch_decode(outputs[:, inputs.shape[1]:])[0]
        answer = f"""\n### order {index}: {row['order']} \n
        comment: {row['comment_text']} \n
        response: \n
        {text}
        \n
        """
        f.write(answer)
        print(f"{index} Done.")

KeyboardInterrupt:

# Test with a simplified prompt

In [ ]:
simplified_prompt = """Assign a numeric score to each of these foods based on the meaning of the comment:
foods : ['چلو کباب کوبیده مخصوص دو سیخ (110 گرمی)', 'چلو کباب لقمه', 'نوشابه بطری کوکا کولا', 'سالاد فصل']
comment : [سالادش خیلی تلخ و بد مزه بود
کباب هم بوی بدی میداد]

Output in this format:
```food1 : <score_for_food1> ,
   food2 : <score_for_food2>
   and so on...
```
"""

system_role = "You are a helpful digital assisstant having brilliant analytical skills."

messages = [{"role": "system",
             "content": f"{system_role}"},
 {"role": "user",
  "content": f"{simplified_prompt}"}]

In [ ]:
inputs = tokenizer.apply_chat_template(messages, add_generation_prompt=True, return_tensors="pt")

outputs = model.generate(inputs, max_new_tokens=100)
text = tokenizer.batch_decode(outputs)[0]
print(text)

You are not running the flash-attention implementation, expect numerical differences.

<s><|user|>
Assign a numeric score to each of these foods based on the meaning of the comment:
foods : ['چلو کباب کوبیده مخصوص دو سیخ (110 گرمی)', 'چلو کباب لقمه', 'نوشابه بطری کوکا کولا', 'سالاد فصل']
comment : [سالادش خیلی تلخ و بد مزه بود
کباب هم بوی بدی میداد]

Output in this format:
```food1 : <score_for_food1> ,
   food2 : <score_for_food2>
   and so on...
```
<|end|>
<|assistant|>
```
چلو کباب کوبیده مخصوص دو سیخ (110 گرمی) : -2 ,
چلو کباب لقمه : -1 ,
نوشابه بطری کوکا کولا : -3 ,
سالاد فصل : -4

# Test with original prompts

In [ ]:
prompt_enhancements = """Suppose that we are working in the domain of a food delivery app.
Here is the list of foods and beverages ordered by a user, let's call it 'UserOrder':
UserOrder: '['چلو کباب کوبیده مخصوص دو سیخ (110 گرمی)', 'چلو کباب لقمه', 'نوشابه بطری کوکا کولا', 'سالاد فصل']'

After receiving the 'UserOrder', here is the user's comment (review) about their experience having UserOrder (called 'UserComment'):
UserComment: 'سالادش خیلی تلخ و بد مزه بود
کباب هم بوی بدی میداد'
As you see, UserComment expresses the user's satisfaction with the food quality and services delivered.

If available, here is the list of ingredients per each food included in the UserOrder (called 'FoodIngredients'):
FoodIngredients: {'چلو کباب کوبیده مخصوص دو سیخ (110 گرمی)': 'کباب کوبیده گوشت گوسفندی، 350 گرم برنج ایرانی، دورچین: گوجه کبابی، خیارشور، پیاز، لیمو', 'چلو کباب لقمه': 'یک سیخ کباب لقمه گوشت گوسفندی 250 گرمی، 350 گرم برنج ایرانی، دورچین: گوجه کبابی، خیارشور، پیاز، لیمو', 'نوشابه بطری کوکا کولا': '300 میلی لیتر', 'سالاد فصل': 'یک نفره، کاهو، کلم، خیار، گوجه فرنگی، هویج رنده شده'}

Having the context provided, your task is to evaluate the food quality and services delivered based on UserComment. In other words, you should assign a score per each food and services delivered. Let's think step by step:
First, inspect the UserComment precisely.

Then, Based on UserComment, assign a score per each of the foods ordered (an integer between 0 and 5). In other words, all the food titles mentioned in the UserOrder must get a score field. If UserComment does not include any specific review for any of the food ordered, set the corresponding food score to 'Nan'.
*ATTENTION*: In this step, if UserComment is a general positive or negative comment and does not specify any particular food item, apply it to all food items ordered.
For example: Having UserComment='همه چی عالی', all the food items ordered will get a 5 score.

For the next step, refer to UserComment again. Based on UserComment, assign a score per each service provided (if any). To achieve this, first, you need to specify the relevant part of the UserComment expressing the user's experience with the service. Then, classify that service into one of these categories:
'[Delivery time, Quality of packaging, Cost of packaging, Cost per value of foods, Overall quality, Staff behavior, Food temperature, Delivered food not as ordered]'
After that, assign a score (an integer between 0 and 5) to that service based on part_of_comment. Feel free to set the service score as 'Nan' if the user seems unclear about the satisfaction with the service provided.

*ATTENTION*: As you see, the UserComment is in Persian. Thus, be mindful of any different Persian idioms or slang used and their actual meanings.

Finally, Based on the information inferred in the previous steps, generate JSON about the foods and services in this format:
```
{
    qualities: [
        {
            "food_title": "",
            "food_rate": ""
        }
    ],
    services: [
        {
            part_of_comment: "",
            service_rate: "",
            service_classified: ""
        }
    ]
}
```
Output only the JSON. Do not output any extra information or explanations.

"""

In [ ]:
messages = [{"role": "system",
             "content": f"{system_role}"},
 {"role": "user",
  "content": f"{prompt_enhancements}"}]


inputs = tokenizer.apply_chat_template(messages, add_generation_prompt=True, return_tensors="pt")

outputs = model.generate(inputs, max_new_tokens=2000, temperature=0.0)
text = tokenizer.batch_decode(outputs)[0]
print(text)

<s><|user|>
Suppose that we are working in the domain of a food delivery app.
Here is the list of foods and beverages ordered by a user, let's call it 'UserOrder':
UserOrder: '['چلو کباب کوبیده مخصوص دو سیخ (110 گرمی)', 'چلو کباب لقمه', 'نوشابه بطری کوکا کولا', 'سالاد فصل']'

After receiving the 'UserOrder', here is the user's comment (review) about their experience having UserOrder (called 'UserComment'):
UserComment: 'سالادش خیلی تلخ و بد مزه بود
کباب هم بوی بدی میداد'
As you see, UserComment expresses the user's satisfaction with the food quality and services delivered.

If available, here is the list of ingredients per each food included in the UserOrder (called 'FoodIngredients'):
FoodIngredients: {'چلو کباب کوبیده مخصوص دو سیخ (110 گرمی)': 'کباب کوبیده گوشت گوسفندی، 350 گرم برنج ایرانی، دورچین: گوجه کبابی، خیارشور، پیاز، لیمو', 'چلو کباب لقمه': 'یک سیخ کباب لقمه گوشت گوسفندی 250 گرمی، 350 گرم برنج ایرانی، دورچین: گوجه کبابی، خیارشور، پیاز، لیمو', 'نوشابه بطری کوکا کولا': '300 میلی لیتر', 'سالاد فصل': 'یک نفره، کاهو، کلم، خیار، گوجه فرنگی، هویج رنده شده'}

Having the context provided, your task is to evaluate the food quality and services delivered based on UserComment. In other words, you should assign a score per each food and services delivered. Let's think step by step:
First, inspect the UserComment precisely.

Then, Based on UserComment, assign a score per each of the foods ordered (an integer between 0 and 5). In other words, all the food titles mentioned in the UserOrder must get a score field. If UserComment does not include any specific review for any of the food ordered, set the corresponding food score to 'Nan'.
*ATTENTION*: In this step, if UserComment is a general positive or negative comment and does not specify any particular food item, apply it to all food items ordered.
For example: Having UserComment='همه چی عالی', all the food items ordered will get a 5 score.

For the next step, refer to UserComment again. Based on UserComment, assign a score per each service provided (if any). To achieve this, first, you need to specify the relevant part of the UserComment expressing the user's experience with the service. Then, classify that service into one of these categories:
'[Delivery time, Quality of packaging, Cost of packaging, Cost per value of foods, Overall quality, Staff behavior, Food temperature, Delivered food not as ordered]'
After that, assign a score (an integer between 0 and 5) to that service based on part_of_comment. Feel free to set the service score as 'Nan' if the user seems unclear about the satisfaction with the service provided.

*ATTENTION*: As you see, the UserComment is in Persian. Thus, be mindful of any different Persian idioms or slang used and their actual meanings.

Finally, Based on the information inferred in the previous steps, generate JSON about the foods and services in this format:
```
{
    qualities: [
        {
            "food_title": "",
            "food_rate": ""
        }
    ],
    services: [
        {
            part_of_comment: "",
            service_rate: "",
            service_classified: ""
        }
    ]
}
```
Output only the JSON. Do not output any extra information or explanations.

<|end|>
<|assistant|>
{
    "qualities": [
        {
            "food_title": "چلو کباب کوبیده مخصوص دو سیخ (110 گرمی)",
            "food_rate": "2"
        },
        {
            "food_title": "چلو کباب لقمه",
            "food_rate": "2"
        },
        {
            "food_title": "نوشابه بطری کوکا کولا",
            "food_rate": "3"
        },
        {
            "food_title": "سالاد فصل",
            "food_rate": "1"
        }
    ],
    "services": [
        {
            "part_of_comment": "سالادش خیلی تلخ و بد مزه بود",
            "service_rate": "1",
            "service_classified": "Overall quality"
        }
    ]
}<|end|>

In [ ]:
main_prompt = """Your task is three things that i mentioned below:
    1_ For each food item, you need to:
        - Assign a rating based on quality of food(an integer between 0 and 5)
    2_ For a comment, you need to:
        - Extract the part of the comment that explain about quality of service.(part_of_comment)
        - Classify service based on this qualities: Delivery time, Quality of packaging, Cost of packaging, Cost per value of foods, Overall quality, Staff behavior, Food temperature, Delivered food not as ordered
        - Assign a rating based on quality of service(an integer between 0 and 5)
        - If the comment was not in service classifier fill part_of_comment, service_rate, service_classified with 'Nan'.
        - The comment might have more than one service.
    3_ Your output must be sorted look like below. Don't use extra information and explanation.
                {{
    qualities: [
        {{
            food_title: 'food_title',
            food_rate: 'food_rate'
        }}
    ],
    services: [
        {{
            part_of_comment: 'part_of_comment',
            service_rate: 'service_rate',
            service_classified: 'service_classified'
        }}
    ]
}}
    The Data is below within the three backticks.
    ```
    comment : سالادش خیلی تلخ و بد مزه بود
کباب هم بوی بدی میداد
    materials : {'چلو کباب کوبیده مخصوص دو سیخ (110 گرمی)': 'کباب کوبیده گوشت گوسفندی، 350 گرم برنج ایرانی، دورچین: گوجه کبابی، خیارشور، پیاز، لیمو',
 'چلو کباب لقمه': 'یک سیخ کباب لقمه گوشت گوسفندی 250 گرمی، 350 گرم برنج ایرانی، دورچین: گوجه کبابی، خیارشور، پیاز، لیمو',
 'نوشابه بطری کوکا کولا': '300 میلی لیتر',
 'سالاد فصل': 'یک نفره، کاهو، کلم، خیار، گوجه فرنگی، هویج رنده شده'}

    foods : ['چلو کباب کوبیده مخصوص دو سیخ (110 گرمی)',
 'چلو کباب لقمه',
 'نوشابه بطری کوکا کولا',
 'سالاد فصل']
    ```
    There is delivery service and customers order one or many different foods and after receiving their food, they can comment on each food item.
    The food items are named in Persian and listed as follows:: ['name of food','name of food', ...].
    The menu of the restaurant and the ingredients of each food item are sorted as follows:
      [{{'foods name': 'materials'}}, {{'foods name': 'materials'}}, ... ]
    pay attention to materials of foods. customer might comment and criticising about materials of food. foods might doesn't have materials.
    analyze the comment and determine which food item it is about.
    if the customer has commented the overall food experience and the comment does not specify which food item the rating is for, you can use comment for all the food items ordered.
    if the customer has commented some foods poorly and has not mentioned other foods or the overall experience, you must fill rate the other foods with 'Nan'.
    if the customer has commented poorly on some food items and has not mentioned other food items or the overall experience, you must not rate on other food items and fill it in with 'Nan'
    If the customer commented badly on some foods and other parts of the comment were the overall experience, use part of the comment with the overall experience on the other foods. The rate for bad foods must be exactly the same part of the sentences criticizing the foods.
    Pay attention to this two comment. they are rated as 5 for quality of foods: 'خدایییش غذاش خوبه', 'حرف نداره'
"""

In [ ]:
messages = [{"role": "system",
             "content": f"{system_role}"},
 {"role": "user",
  "content": f"{main_prompt}"}]


inputs = tokenizer.apply_chat_template(messages, add_generation_prompt=True, return_tensors="pt")

outputs = model.generate(inputs, max_new_tokens=2000, temperature=0.0)
text = tokenizer.batch_decode(outputs)[0]
print(text)

<s><|user|>
Your task is three things that i mentioned below:
    1_ For each food item, you need to:
        - Assign a rating based on quality of food(an integer between 0 and 5)
    2_ For a comment, you need to:
        - Extract the part of the comment that explain about quality of service.(part_of_comment)
        - Classify service based on this qualities: Delivery time, Quality of packaging, Cost of packaging, Cost per value of foods, Overall quality, Staff behavior, Food temperature, Delivered food not as ordered
        - Assign a rating based on quality of service(an integer between 0 and 5)
        - If the comment was not in service classifier fill part_of_comment, service_rate, service_classified with 'Nan'.
        - The comment might have more than one service.
    3_ Your output must be sorted look like below. Don't use extra information and explanation.
                {{
    qualities: [
        {{
            food_title: 'food_title',
            food_rate: 'food_rate'
        }}
    ],
    services: [
        {{
            part_of_comment: 'part_of_comment',
            service_rate: 'service_rate',
            service_classified: 'service_classified'
        }}
    ]
}}
    The Data is below within the three backticks.
    ```
    comment : سالادش خیلی تلخ و بد مزه بود
کباب هم بوی بدی میداد
    materials : {'چلو کباب کوبیده مخصوص دو سیخ (110 گرمی)': 'کباب کوبیده گوشت گوسفندی، 350 گرم برنج ایرانی، دورچین: گوجه کبابی، خیارشور، پیاز، لیمو',
 'چلو کباب لقمه': 'یک سیخ کباب لقمه گوشت گوسفندی 250 گرمی، 350 گرم برنج ایرانی، دورچین: گوجه کبابی، خیارشور، پیاز، لیمو',
 'نوشابه بطری کوکا کولا': '300 میلی لیتر',
 'سالاد فصل': 'یک نفره، کاهو، کلم، خیار، گوجه فرنگی، هویج رنده شده'}

    foods : ['چلو کباب کوبیده مخصوص دو سیخ (110 گرمی)',
 'چلو کباب لقمه',
 'نوشابه بطری کوکا کولا',
 'سالاد فصل']
    ```
    There is delivery service and customers order one or many different foods and after receiving their food, they can comment on each food item.
    The food items are named in Persian and listed as follows:: ['name of food','name of food', ...].
    The menu of the restaurant and the ingredients of each food item are sorted as follows:
      [{{'foods name': 'materials'}}, {{'foods name': 'materials'}}, ... ]
    pay attention to materials of foods. customer might comment and criticising about materials of food. foods might doesn't have materials.
    analyze the comment and determine which food item it is about.
    if the customer has commented the overall food experience and the comment does not specify which food item the rating is for, you can use comment for all the food items ordered.
    if the customer has commented some foods poorly and has not mentioned other foods or the overall experience, you must fill rate the other foods with 'Nan'.
    if the customer has commented poorly on some food items and has not mentioned other food items or the overall experience, you must not rate on other food items and fill it in with 'Nan'
    If the customer commented badly on some foods and other parts of the comment were the overall experience, use part of the comment with the overall experience on the other foods. The rate for bad foods must be exactly the same part of the sentences criticizing the foods.
    Pay attention to this two comment. they are rated as 5 for quality of foods: 'خدایییش غذاش خوبه', 'حرف نداره'
<|end|>
<|assistant|>
    {{
    qualities: [
        {{
            food_title: 'چلو کباب کوبیده مخصوص دو سیخ (110 گرمی)',
            food_rate: 2
        }},
        {{
            food_title: 'چلو کباب لقمه',
            food_rate: 5
        }},
        {{
            food_title: 'نوشابه بطری کوکا کولا',
            food_rate: 5
        }},
        {{
            food_title: 'سالاد فصل',
            food_rate: 5
        }}
    ],
    services: [
        {{
            part_of_comment: 'سالادش خیلی تلخ و بد مزه بود',
            service_rate: 1,
            service_classified: 'Overall quality'
        }},
        {{
            part_of_comment: 'کباب هم بوی بدی میداد',
            service_rate: 1,
            service_classified: 'Quality of packaging'
        }}
    ]
}}<|end|>

# Test with `pipeline() `

In [ ]:
from google.colab import drive

drive.mount('/content/drive')
%cd 'drive/MyDrive/Projects/Dastpokht/comment_analyzer'

Mounted at /content/drive
/content/drive/MyDrive/Projects/Dastpokht/comment_analyzer

In [ ]:
import pandas as pd

df = pd.read_csv("data/analyzer_result.csv")
df

,comment_text,qualities,services,foods
0,برگر با کیفیت. تحویل سریع. گرم هم رسید غذا.,"{""{\""food_rate\"": \""5\"", \""food_title\"": \""سان...","{""{\""service_rate\"": \""5\"", \""part_of_comment\...","{""{\""product_id\"": 18749645, \""product_title\""..."
1,عالي بود,"{""{\""food_rate\"": \""5\"", \""food_title\"": \""است...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""product_id\"": 18748885, \""product_title\""..."
2,خیلی خوب بود ممنون,"{""{\""food_rate\"": \""5\"", \""food_title\"": \""آمر...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""product_id\"": 18748883, \""product_title\""..."
3,کیفیت برگرا عالی ولی سیب زمینی خیلی معمولی,"{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""ن...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""product_id\"": 18749778, \""product_title\""..."
4,خیلی خوب بود,"{""{\""food_rate\"": \""5\"", \""food_title\"": \""آمر...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""product_id\"": 18748883, \""product_title\""..."
...,...,...,...,...
5147,گوشتش خام بود و کامل نپخته بود ، سیب‌زمینی‌ها ...,"{""{\""food_rate\"": \""0\"", \""food_title\"": \""ماش...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""product_id\"": 20588637, \""product_title\""..."
5148,بهترین برگر,"{""{\""food_rate\"": \""5\"", \""food_title\"": \""بیک...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""product_id\"": 20588641, \""product_title\""..."
5149,عالی بود. راضی بودم,"{""{\""food_rate\"": \""5\"", \""food_title\"": \""نوش...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""product_id\"": 20593426, \""product_title\""..."
5150,واقعا برگرهاتون حرف نداره ،فقط برای این کیفیت ...,"{""{\""food_rate\"": \""4\"", \""food_title\"": \""اول...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""product_id\"": 20588633, \""product_title\""..."
5151,غذا گرم نبود اصلا,"{""{\""food_rate\"": \""0\"", \""food_title\"": \""اور...","{""{\""service_rate\"": \""0\"", \""part_of_comment\...","{""{\""product_id\"": 20588650, \""product_title\""..."

In [ ]:
df["foods"][0]

'{"{\\"product_id\\": 18749645, \\"product_title\\": \\"ساندویچ رست بیف چدار لارج\\", \\"product_description\\": \\"240 گرم گوشت سردست گوساله رست بیف، پیاز کریسپی، پنیر چدار، سس رد رنچ، نان برگر مخصوص بیف لاین\\"}","{\\"product_id\\": 18749748, \\"product_title\\": \\"سیمپل فرایز\\", \\"product_description\\": \\"سیب زمینی سرخ شده\\"}"}'

In [ ]:
import ast

es = list(ast.literal_eval(df["foods"][0]))
es

['{"product_id": 18749645, "product_title": "ساندویچ رست بیف چدار لارج", "product_description": "240 گرم گوشت سردست گوساله رست بیف، پیاز کریسپی، پنیر چدار، سس رد رنچ، نان برگر مخصوص بیف لاین"}',
 '{"product_id": 18749748, "product_title": "سیمپل فرایز", "product_description": "سیب زمینی سرخ شده"}']

In [ ]:
type(es[0])

str

In [ ]:
a = ast.literal_eval(es[0])

In [ ]:
type(a)

dict

In [ ]:
a.keys()

dict_keys(['product_id', 'product_title', 'product_description'])

In [ ]:
samples["foods"][0]

'{"{\\"product_id\\": 22922785, \\"product_title\\": \\"پیتزا سیر و استیک ایتالیایی یک نفره (25 سانتی متری)\\", \\"product_description\\": \\"خمیر پیتزا ایتالیایی، استیک دست ساز گوشت گوساله، پنیر پیتزا، قارچ، زیتون سیاه، پیاز، سیر، فلفل دلمه ای، کره طعم دار\\"}"}'

In [ ]:
samples["order"] = ""
samples["ingredients"] = ""
samples

,comment_text,qualities,services,foods,order,ingredients
0,افتضاح تا بحال به عمرم پیتزا به این بدی ندیده ...,"{""{\""food_rate\"": \""0\"", \""food_title\"": \""پیت...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""product_id\"": 22922785, \""product_title\""...",,
1,اصلا طعم قرمه سبزی نداشت یعنی اگر خودم سفارش ن...,"{""{\""food_rate\"": \""1\"", \""food_title\"": \""چلو...",{},"{""{\""product_id\"": 6391220, \""product_title\"":...",,
2,چلوکباب سماغ نداشت,"{""{\""food_rate\"": \""0\"", \""food_title\"": \""چلو...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""product_id\"": 23638165, \""product_title\""...",,
3,حتما دوبار سفارش می دم,"{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""ز...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""product_id\"": 5545444, \""product_title\"":...",,
4,عالی,"{""{\""food_rate\"": \""5\"", \""food_title\"": \""خور...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""product_id\"": 20430113, \""product_title\""...",,
...,...,...,...,...,...,...
95,طعم برگر بشدت بد و بی مزه بود سیب زمینی های مخ...,"{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""ن...","{""{\""service_rate\"": \""0\"", \""part_of_comment\...","{""{\""product_id\"": 6256725, \""product_title\"":...",,
96,فلفل کبابی نداشت و نونش کم بود نسبت به ۴ سیخی ...,"{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""خ...","{""{\""service_rate\"": \""2\"", \""part_of_comment\...","{""{\""product_id\"": 21436811, \""product_title\""...",,
97,حجم مواد خوب بود و مزه خوبی داشت نسبتا ولی پیت...,"{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""س...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""product_id\"": 24755883, \""product_title\""...",,
98,عالی,"{""{\""food_rate\"": \""5\"", \""food_title\"": \""چلو...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""product_id\"": 7588082, \""product_title\"":...",,
99,پول پیک پانزده هزار تومن نمیرزه,"{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""س...","{""{\""service_rate\"": \""1\"", \""part_of_comment\...","{""{\""product_id\"": 19131318, \""product_title\""...",,

In [ ]:
samples.loc[0, "order"] = "dsdsd"
samples.loc[0]

comment_text    افتضاح تا بحال به عمرم پیتزا به این بدی ندیده ...
qualities       {"{\"food_rate\": \"0\", \"food_title\": \"پیت...
services        {"{\"service_rate\": \"Nan\", \"part_of_commen...
foods           {"{\"product_id\": 22922785, \"product_title\"...
order                                                       dsdsd
ingredients
Name: 0, dtype: object

In [ ]:
for index, row in samples.iterrows():
    food_titles = []
    ingredients = {}
    products = list(ast.literal_eval(row["foods"]))
    for product in products:
        product = ast.literal_eval(product)
        food = product["product_title"]
        food_titles.append(food)
        ingredients[food] = product['product_description']
        samples.loc[index, "order"] = str(food_titles)
        samples.loc[index, "ingredients"] = str(ingredients)
    print(food_titles, ingredients)

['پیتزا سیر و استیک ایتالیایی یک نفره (25 سانتی متری)'] {'پیتزا سیر و استیک ایتالیایی یک نفره (25 سانتی متری)': 'خمیر پیتزا ایتالیایی، استیک دست ساز گوشت گوساله، پنیر پیتزا، قارچ، زیتون سیاه، پیاز، سیر، فلفل دلمه ای، کره طعم دار'}
['چلو خورشت قورمه سبزی', 'نوشابه شیشه ای کوکا کولا'] {'چلو خورشت قورمه سبزی': '200 گرم خورشت٬ 70 گرم گوشت گوسفندی٬ 400 گرم برنج ایرانی٬ ته دیگ زعفرانی', 'نوشابه شیشه ای کوکا کولا': '250 میلی لیتر\r\n'}
['چلو کباب\u200c کوبیده مخصوص اقتصادی'] {'چلو کباب\u200c کوبیده مخصوص اقتصادی': 'یک سیخ کباب کوبیده مخصوص مخلوط گوشت گوساله و گوسفندی 120 گرمی، 300 گرم برنج ایرانی، 25 گرم نثار زعفرانی (خلال پسته و بادام و روغن کرمانشاهی)، گوجه کبابی، فلفل کبابی، سماق'}
['زرشک پلو با مرغ سس پز ران'] {'زرشک پلو با مرغ سس پز ران': 'یک تکه مرغ سس پز 350 گرمی، 450 گرم زرشک پلو با برنج ایرانی'}
['خوراک جوجه کباب ترش گیلانه'] {'خوراک جوجه کباب ترش گیلانه': 'یک سیخ جوجه کباب ترش سینه مرغ طعم دار شده با سس انار و گردو 400 گرمی، دورچین: گوجه کبابی، فلفل کبابی'}
['نوشابه قوطی فانتا پرتقالی', 'نوشابه قوطی اسپرایت', 'نوشابه قوطی کوکاکولا', 'چلو جوجه کباب زعفرانی یک سیخ سینه مرغ 210 گرمی', 'شله زرد'] {'نوشابه قوطی فانتا پرتقالی': '330 میلی لیتر', 'نوشابه قوطی اسپرایت': '330 میلی لیتر', 'نوشابه قوطی کوکاکولا': '330 میلی لیتر', 'چلو جوجه کباب زعفرانی یک سیخ سینه مرغ 210 گرمی': 'جوجه کباب، 350 گرم برنج ایرانی، دورچین: گوجه کبابی، فلفل کبابی', 'شله زرد': '450 گرم، برنج ایرانی، زعفران، کره، تزیین شده با پودر نارگیل، پودر دارچین'}
['اسپشیال برگر گوسفندی'] {'اسپشیال برگر گوسفندی': 'یک عدد برگر دست ساز گوشت گوسفندی 180 گرمی، مغز قلم گوساله، سس قارچ، گوجه، خیارشور، کاهو، چیپس دست ساز، پنیر دیپ چدار، نان برگر'}
['پیتزا هالوپینا استیک کوچک (24 سانتی متر)', 'ماءالشعیر کوچک'] {'پیتزا هالوپینا استیک کوچک (24 سانتی متر)': 'راسته گوساله، فلفل هالوپینو (تند)، پنیر هلندی، پنیر موزارلا، سس مخصوص در ب در', 'ماءالشعیر کوچک': '300 میلی لیتر'}
['سالاد سزار (دو نفره)'] {'سالاد سزار (دو نفره)': 'سینه مرغ گریل شده تکه ای 200 گرمی، کاهو، پنیر پارمسان، گوجه'}
['پاپاس'] {'پاپاس': '120 گرم سیب زمینی تنوری، قارچ، پنیر پیتزا، سس مخصوص'}
['ساندویچ دونر کباب مخلوط'] {'ساندویچ دونر کباب مخلوط': 'دونر گوشت و مرغ، مخلفات گرم شامل قارچ گوجه پیاز، و مخلفات سرد شامل خیارشور، پیاز جعفری، سس مخصوص، نان چارکی سحرمخصوص دونر'}
['خوراک جوجه کباب سینه مرغ (200 گرم)', 'خورشت قورمه سبزی', 'چلو اکبر جوجه', 'چلو کره'] {'خوراک جوجه کباب سینه مرغ (200 گرم)': 'یک سیخ جوجه کباب، دورچین: خیارشور، پیاز و جعفری، (سرو بدون نان)', 'خورشت قورمه سبزی': '250 گرم خورشت قورمه سبزی، 80 گرم گوشت گوساله تکه ای، بدون برنج', 'چلو اکبر جوجه': '500 گرم اکبر جوجه (نصف یک جوجه کامل)، رب انار، 400 گرم برنج ایرانی، دورچین: خیارشور، پیاز و جعفری، (سرو بدون نان)', 'چلو کره': '400 گرم برنج ایرانی، ته دیگ زعفرانی، زرشک زعفران'}
['خوراک جوجه کباب ترش شمالی'] {'خوراک جوجه کباب ترش شمالی': 'یک سیخ جوجه کباب سینه مرغ طعم دار شده با سس انار 230 گرمی، دورچین: گوجه کبابی، هویج، کره، یک عدد نان لواش'}
['خوراک کباب کوبیده بره ممتاز', 'دوغ بطری گلپایگانی کوچک'] {'خوراک کباب کوبیده بره ممتاز': 'کباب کوبیده گوشت بره 320 گرمی، دورچین: نارنج، فلفل کبابی، گوجه کبابی، پیاز، یک عدد نان تافتون سنتی', 'دوغ بطری گلپایگانی کوچک': '330 میلی لیتر'}
['خوراک کتف کبابی'] {'خوراک کتف کبابی': 'یک سیخ کتف کبابی (7 تکه)، دورچین: لیموترش، گوجه کبابی، فلفل کبابی، پیاز، نان'}
['کفته کباب بوقلمون'] {'کفته کباب بوقلمون': '220 گرم کفتە کباب سینە و ران مرغ بوقلمون، دورچین: 120 گرم برنج ایرانی مزە دار شدە، 180 گرم سیب زمینی تنوری، فلفل تنوری، پیاز و جعفری، نان، ھمراە با یک عدد سس سیر دست ساز یک نفرە، یک عدد سس گوجە دست ساز یک نفرە'}
['پیتزا مرغ دودی (یک نفره)', 'سیب زمینی سرخ کرده', 'نوشابه خانواده کوکاکولا', 'قارچ سوخاری', 'پیتزا کمبو یک نفره (30 سانتیمتری)', 'پیتزا سیر و استیک یک نفره (30 سانتیمتری)', 'نوشابه خانواده اسپرایت'] {'پیتزا مرغ دودی (یک نفره)': 'خمیر پیتزا ایتالیایی چاودار، سینه مرغ، سس باربیکیو، سس مخصوص باگت', 'سیب زمینی سرخ کرده': '2 تکه مرغ، ادویه سوخاری، سیب زمینی سرخ کرده، سالاد کلم، یک عدد نان بروتچن', 'نوشابه خانواده کوکاکولا': '1.5 لیتر', 'قارچ سوخاری': '200 تا 220 گرم قارچ سوخاری', 'پیتزا کمبو یک نفره (30 سانتیمتری)': 'خمیر پیتزا ایتالیایی چاودار، ژامبون گوشت، ژامبون مرغ، قارچ، فلفل دلمه ای، زیتون، ذرت، پپرونی، پیاز، سس مخصوص باگت', 'پیتزا سیر و استیک یک نفره (30 سانتیمتری)': 'خمیر پیتزا ایتالیایی چاودار، راسته گوساله، روغن زیتون، سیر تازه، سس مخصوص باگت', 'نوشابه خانواده اسپرایت': '1.5 لیتر'}
['چلو گردن گوسفندی', 'ساندویچ شاورما گوشت', 'خوراک کباب عنتبلی'] {'چلو گردن گوسفندی': '500 گرم گردن گوسفندی سس پز، 350 گرم برنج ایرانی', 'ساندویچ شاورما گوشت': '200 گرم گوشت مخلوط ران بره و فیله گوساله مزه دار شده، سبزیجات مخصوص، ادویه مخصوص، نان عربی، دورچین: سیب زمینی سرخ شده', 'خوراک کباب عنتبلی': 'یک سیخ کباب عنتبلی گوشت مخلوط گوساله و گوسفندی 180 گرمی، دورچین: گوجه کبابی، پیاز جعفری، ترشی کلم قرمز، لیمو ترش، یک تکه نان تافتون'}
['ساندویچ کریسپی', 'نوشابه قوطی کوکا کولا'] {'ساندویچ کریسپی': 'دوعدد فیله سوخاری نرمال، سس ویژه، گوجه، خیارشور، کاهو، نان باگت', 'نوشابه قوطی کوکا کولا': '330 میلی لیتر'}
['خوراک کباب کوبیده', 'دوغ خانواده سنتی', 'نان، ریحان و پنیر'] {'خوراک کباب کوبیده': 'یک سیخ کباب کوبیده گوشت گوسفندی 220 گرمی، دورچین: گوجه کبابی، فلفل کبابی، یک عدد نان تافتون تنوری مخصوص', 'دوغ خانواده سنتی': 'یک لیتر', 'نان، ریحان و پنیر': 'یک نفره، پنیر صبحانه، ریحان، دو عدد نان تافتون تنوری مخصوص'}
['سیب زرد 1 کیلوگرم ± 50 گرم', 'کیوی 1 کیلوگرم ± 50 گرم', 'هویج  1 کیلوگرم ± 50 گرم', 'پرتقال شمال 1 کیلوگرم ± 50 گرم', 'انار  1 کیلوگرم ± 50 گرم', 'خیار درختی  1 کیلوگرم ± 50 گرم'] {'سیب زرد 1 کیلوگرم ± 50 گرم': '', 'کیوی 1 کیلوگرم ± 50 گرم': '', 'هویج  1 کیلوگرم ± 50 گرم': '', 'پرتقال شمال 1 کیلوگرم ± 50 گرم': '', 'انار  1 کیلوگرم ± 50 گرم': '', 'خیار درختی  1 کیلوگرم ± 50 گرم': ''}
['سالاد شیرازی', 'زرشک پلو با مرغ سرخ کرده ران'] {'سالاد شیرازی': 'یک نفره، گوجه، خیار، پیاز، نعنا، لیموترش، دست ساز', 'زرشک پلو با مرغ سرخ کرده ران': 'یک تکه مرغ سرخ شده 450 گرمی، 300 گرم زرشک پلو با برنج ایرانی'}
['استیک سینه مرغ گریل'] {'استیک سینه مرغ گریل': '250 گرم سینه مرغ گریل شده، پوره سیب زمینی، میکس سبزیجات چینی، کدو گریل مزه دار شده، قارچ مزه دار شده، اسفناج مرینت شده، سس قارچ مخصوص گریل باکس'}
['خوراک کباب کوبیده ممتاز'] {'خوراک کباب کوبیده ممتاز': '2 سیخ کوبیده 135گرمی گوسفندی و گوساله مخلوط، نان تافتون، لیمو'}
['سالاد اسفناج و موتزارلا', 'فرایز', 'آلفردو', 'نوشابه قوطی کوکا کولا'] {'سالاد اسفناج و موتزارلا': 'کیل، اسفناج، موتزارلا تازه، کرن بری خشک، کینوا، سس سرکه عسل ( 200 گرم محصول نهایی)', 'فرایز': 'سیب زمینی سرخ کرده، پنیر چدار،بیکن', 'آلفردو': 'پاستا پنه ( 200 گرم ) ، قارچ ، فیله مرغ، خامه، پنیر پارمزان، پنیر رومانو، کره کوژن', 'نوشابه قوطی کوکا کولا': '330 میلی لیتر'}
['پیتزا رست بیف آمریکایی یک نفره (24 سانتی متری)', 'پاستا چیکن آلفردو'] {'پیتزا رست بیف آمریکایی یک نفره (24 سانتی متری)': 'خمیر پیتزا آمریکایی، رست بیف، قارچ، فلفل دلمه ای، پنیر پیتزا، زیتون', 'پاستا چیکن آلفردو': ' پاستا پنه، سس آلفردو، شنسل مرغ طعم دار شده، قارچ، پنیر پارمسان'}
['پیتزا مخصوص هات آمریکایی یک نفره (22 سانتی متری)'] {'پیتزا مخصوص هات آمریکایی یک نفره (22 سانتی متری)': 'خمیر پیتزا آمریکایی، کالباس، پپرونی، هات داگ، قارچ، فلفل دلمه ای، ذرت، زیتون، پنیر پارمسان'}
['چلو جوجه کباب معمولی'] {'چلو جوجه کباب معمولی': 'یک سیخ جوجه کباب سینه 170 گرمی، گوجه کبابی، لیمو، 350 گرم برنج ایرانی، کره\nوزن غذاها ها به صورت تقریبی و به همراه برنج ایرانی می باشد'}
['ساندویچ وجیتاس سرد یک نفره'] {'ساندویچ وجیتاس سرد یک نفره': 'سیب زمینی، سبزیجات معطر، پنیر، چیپس، پیاز و جعفری، گوجه، خیارشور، سس مخصوص باماهاس، نان باگت'}
['املت با قارچ', 'املت با سوسیس'] {'املت با قارچ': '2 عدد تخم مرغ، گوجه فرنگی، قارچ، دورچین: پیاز، فلفل تند، لیمو، خیارشور، نصف نان بربری', 'املت با سوسیس': '2 عدد تخم مرغ، گوجه فرنگی، سوسیس 80% گوشت، دورچین: پیاز، فلفل تند، لیمو، خیارشور، نصف نان بربری'}
['چلو جوجه کباب معمولی اقتصادی'] {'چلو جوجه کباب معمولی اقتصادی': 'یک سیخ جوجه سینه مرغ 250 گرمی، 350 گرم برنج ایرانی، دورچین: یک عدد گوجه کبابی، یک عدد کره، لیمو'}
['چلو جوجه کباب مخصوص ران (300 گرمی)'] {'چلو جوجه کباب مخصوص ران (300 گرمی)': '1 سیخ 300 گرمی  جوجه ران 400 گرم برنج کره گوجه فلفل ته دیگ'}
['فان چیکن'] {'فان چیکن': '4 تکه کوچک سینه مرغ سوخاری شده'}
['چاباتا بیف ماشروم'] {'چاباتا بیف ماشروم': 'گوشت ران گوساله، قارچ، پیاز کاراملی، ادویه، برگ اسفناج،  سبزیجات معطر، نان چاباتا'}
['ران مرغ بریان با دورچین'] {'ران مرغ بریان با دورچین': '400 گرم مرغ بریان، دورچین: کاهو. گوجه. خیارشور. سیب زمینی. نان باگت'}
['ران مرغ بدون پوست  1 کیلوگرم', 'کامل'] {'ران مرغ بدون پوست  1 کیلوگرم': 'مناسب گریل، سوخاری یا پخت به صورت سس پز، ارایه به صورت خرد شده و به صورت با استخوان یا بدون استخوان به درخواست شما در بسته بندی بهداشتی', 'کامل': 'وزن ضایعات در هر کیلوگرم بین 150 تا 250 گرم،\r\nمناسب بریان، گریل، سوخاری یا پخت به صورت سس پز،\r\nارایه به صورت خرد شده، به صورت با استخوان یا بدون استخوان به درخواست شما در بسته بندی بهداشتی'}
['ساندویچ هات داگ تنوری'] {'ساندویچ هات داگ تنوری': 'یک عدد هات داگ 80% گوشت ویژه، پنیر پیتزا، قارچ، ذرت، خیار شور، گوجه، کاهو، نان نیم تخت بزرگ فرانسوی'}
['سالاد سزار با مرغ گریل'] {'سالاد سزار با مرغ گریل': 'سینه مرغ گریل شده، کاهو، پنیر پارمسان، نان کروتان، گوجه گیلاسی، زیتون سیاه، سس سزار مخصوص'}
['پیتزا وجی (وجیترین)'] {'پیتزا وجی (وجیترین)': 'خمیر پیتزا ایتالیایی 30 سانتی\u200cمتری، بادمجان، کدو، پیاز، فلفل دلمه، قارچ، ذرت، سیر، سان رایزتماتو، سس پستو، سس گوجه خانگی، موزارلا'}
['حلیم یک کیلو گرم'] {'حلیم یک کیلو گرم': 'گندم، گوشت گوسفندی، شکر، دارچین، کنجد، روغن'}
['باقالی پلو با گردن گوسفندی'] {'باقالی پلو با گردن گوسفندی': '"650 تا700گرم گردن گوسفندی با 300 تا 350گرم برنج ایرانی با باقالی و شوید تازه، \r\nزعفران ایرانی، روغن حیوانی خوش عطر و فلفل کبابی. \r\nدورچین: پیاز خلالی سماقی، کدو خام، هویج پخته، فلفل کبابی و لیمو. "\r\n'}
['پیتزا رست بیف', 'پاستا بلونز', 'بال مرغ تریاکی', 'سس سیر اضافه', 'ماءالشعیر قوطی هی جو  کلاسیک'] {'پیتزا رست بیف': 'سس گوجه فرنگی، پنیر بلوچیز، فیله گوساله ریش ریش شده، سیر تازه، هات داگ اسلایس، اسفناج و گوجه فرنگی', 'پاستا بلونز': 'اسپاگتی، گوشت چرخ کرده، قارچ تازه، پیاز، سیر تازه و سس بلونز', 'بال مرغ تریاکی': '6تکه بال سرخ شده، به همراه سس تریاکی', 'سس سیر اضافه': '50گرم سس سیر', 'ماءالشعیر قوطی هی جو  کلاسیک': 'نوشیدنی مالت ساده330 میلی لیتر'}
['ساندویچ کوکتل آرژانتینی یک نفره'] {'ساندویچ کوکتل آرژانتینی یک نفره': 'کوکتل بخارپز ممتاز میکاییلیان، پیاز و جعفری، گوجه، خیارشور، سس مخصوص باماهاس، نان باگت'}
['چلو کباب لقمه مخصوص'] {'چلو کباب لقمه مخصوص': '2 سیخ کباب لقمه مخصوص مخلوط گوشت گوساله و گوسفندی 120 گرمی، 350 گرم برنج مخلوط ایرانی و خارجی، کره٬ دورچین: گوجه کبابی، ترشی کلم قرمز'}
['عدسی'] {'عدسی': 'عدس ، پیاز ، سیب زمینی ، لیموترش'}
['استامبولی'] {'استامبولی': '75 گرم گوشت گوساله تکه ای، 350 گرم استامبولی با برنج ایرانی، ته دیگ زعفرانی'}
['خوراک کباب کوبیده دو سیخ'] {'خوراک کباب کوبیده دو سیخ': 'کباب کوبیده گوشت گوسفندی 120 گرمی، دورچین: گوجه کبابی، فلفل کبابی، یک عدد نان لواش'}
['چلو خورشت قیمه با سیب زمینی', 'نوشابه قوطی کوکا کولا'] {'چلو خورشت قیمه با سیب زمینی': '300 گرم خورشت قیمه سیب زمینی٬ 60 گرم گوشت گوساله٬ 50 گرم سیب زمینی سرخ شده٬ 300 گرم برنج ایرانی', 'نوشابه قوطی کوکا کولا': '330 میلی لیتر'}
['چلو کباب وزیری'] {'چلو کباب وزیری': 'یک سیخ جوجه کباب سینه مرغ 200 گرمی، یک سیخ کباب کوبیده مخلوط گوشت گوساله و گوسفندی 100 گرمی، 400 گرم برنج ایرانی، کره حیوانی، ته دیگ زعفرانی، گوجه کبابی'}
['خوراک کباب کوبیده مخصوص (۳۰ سانتی متری)', 'چلو ساده'] {'خوراک کباب کوبیده مخصوص (۳۰ سانتی متری)': 'یک سیخ کباب کوبیده گوشت گوسفندی 260 گرمی، دورچین روز، نان', 'چلو ساده': '400 گرم برنج ایرانی'}
['کباب کوبیده (دو سیخ)', 'خوراک مرغ سرخ شده'] {'کباب کوبیده (دو سیخ)': '2 سیخ کباب کوبیده مخلوط گوشت گوساله و گوسفندی 100 گرمی، دورچین، نان', 'خوراک مرغ سرخ شده': 'یک عدد ران مرغ سرخ کرده 350 گرمی، پیاز یا خیارشور'}
['ساندویچ هات داگ مرگز با قارچ و پنیر'] {'ساندویچ هات داگ مرگز با قارچ و پنیر': 'هات داگ گوشت تازه 90%، قارچ، پنیر موزارلا، پوره سیب زمینی، پیاز جعفری'}
['ساندویچ هات بیتس'] {'ساندویچ هات بیتس': '2 عدد ساندویچ مینی ھات داگ، نان شرکتی، قارچ و یک ورق پنیر گودا، سس مخصوص'}
['چیلی چیکن برگر', 'نوشابه قوطی کوکا کولا'] {'چیلی چیکن برگر': '120 گرم سینه مرغ سوخاری اسپایسی، پنیر چدار، کاهو، گوجه، نان برگر', 'نوشابه قوطی کوکا کولا': '330 میلی لیتر'}
['لیموناد شیشه ای زمزم', 'ساندویچ مغز و زبان'] {'لیموناد شیشه ای زمزم': '300 میلی لیتر', 'ساندویچ مغز و زبان': '70 گرم مغز و 70 گرم زبان گوساله ریش ریش شده، پیاز و جعفری، گوجه، خیارشور، نان بولکی، سس یک نفره'}
['آب معدنی کوچک دسانی', 'پیتزا 1204 آمریکایی 24 سانتی متری'] {'آب معدنی کوچک دسانی': '500 میلی لیتر', 'پیتزا 1204 آمریکایی 24 سانتی متری': 'خمیر پیتزا آمریکایی 24 سانتی متری، ژامبون مخلوط گوشت و مرغ 90% پپرونی 90%، قارچ، پنیر پیتزا، به همراه یک عدد سس مخصوص و یک عدد سس کچاپ یک نفره'}
['ساندویچ ساباتاسیتاس'] {'ساندویچ ساباتاسیتاس': 'حدود یک کیلو گرم، استیک گوشت، فیله مرغ، گوشت رست شده، کوکتل، قارچ، پنیر، سس مخصوص، گوجه، خیارشور، کاهو، نان باگت'}
['ساندویچ بیکن مخصوص باماهاس سرد کوچک', 'نوشابه قوطی اسپرایت', 'ساندویچ هیولا بیکن سرد کوچک'] {'ساندویچ بیکن مخصوص باماهاس سرد کوچک': 'بیکن بره میکاییلیان 95%، بیکن گوشت میکاییلیان 95%، چیپس، پیاز و جعفری، گوجه، خیارشور، سس مخصوص باماهاس، نان باگت', 'نوشابه قوطی اسپرایت': '330 میلی لیتر', 'ساندویچ هیولا بیکن سرد کوچک': 'بیکن بره میکاییلیان 95%، بیکن گوشت میکاییلیان 95%، ژامبون مرغ میکاییلیان 95%، چیپس، هالوپینو، پیاز و جعفری، گوجه، خیارشور، سس مخصوص باماهاس، نان باگت'}
['چلو خورشت قورمه سبزی'] {'چلو خورشت قورمه سبزی': 'یک پرس خورشت قورمه سبزی، 4 تکه گوشت گوساله، 350 گرم برنج ایرانی'}
['پیتزا مرغ و قارچ آمریکایی 24 سانتی متری', 'ران مرغ سوخاری سه تکه نرمال'] {'پیتزا مرغ و قارچ آمریکایی 24 سانتی متری': 'خمیر پیتزا آمریکایی، سینه مرغ گریل شده، قارچ، زیتون، پنیر پیتزا', 'ران مرغ سوخاری سه تکه نرمال': '3 تکه ران مرغ سوخاری، 180 گرم سیب زمینی سرخ شده، یک عدد سالاد کلم، یک عدد نان بروتچن، به همراه سس شرکتی'}
['رویال برگر ذغالی'] {'رویال برگر ذغالی': 'یک عدد برگر شرکتی 60%، 2 ورق ژامبون گوشت 60%، پنیر پیتزا، قارچ، گوجه، کاهو، خیارشور، نان باگت بزرگ'}
['چلو جوجه کباب سینه'] {'چلو جوجه کباب سینه': 'یک سیخ جوجه کباب سینه مرغ 180 گرمی، 350 گرم برنج ایرانی، دورچین: گوجه کبابی، پیاز، فلفل کبابی، نارنج، یک عدد نان تافتون سنتی'}
['پاستا پنه'] {'پاستا پنه': 'یک نفره، پنه، 170گرم فیله مرغ، پنیر پارمسان، سس قارچ'}
['چلو کباب لقمه'] {'چلو کباب لقمه': 'یک سیخ کباب لقمه گوشت گوسفندی 250 گرمی، 400 گرم برنج ایرانی، دورچین: پیاز، فلفل کبابی، یک عدد گوجه کبابی'}
['نوشابه قوطی سون آپ', 'پیتزا آمریکایی لاکچری یک نفره'] {'نوشابه قوطی سون آپ': '330 میلی لیتر', 'پیتزا آمریکایی لاکچری یک نفره': 'خمیر پیتزا آمریکایی، سس مخصوص، پپرونی رنده شده\u200c، ژامبون بیکن 90%، فلفل دلمه ای، سالامی، (دور خمیر لبه برگردان با مواد میانی سوسیس پنیری)20%تند میباشد'}
['سوپ جو (یک کیلو)'] {'سوپ جو (یک کیلو)': 'جو، هویج، مرغ ریش ریش شده، نخود فرنگی، '}
['چلو خورشت قورمه سبزی', 'دسر تیرامیسو شکلاتی', 'سوپ جو یک نفره'] {'چلو خورشت قورمه سبزی': '200 گرم خورشت٬ 70 گرم گوشت گوسفندی٬ 400 گرم برنج ایرانی٬ ته دیگ زعفرانی', 'دسر تیرامیسو شکلاتی': '75 گرم دسر شارلوت', 'سوپ جو یک نفره': 'یک نفره، 300 گرم، جو، هویج، سینه مرغ ریش ریش شده، رب گوجه فرنگی'}
['پاستا پنه اربیتا میگو'] {'پاستا پنه اربیتا میگو': '700 گرم، 120 گرم میگو، پاستا پنه، سس اربیتا، قارچ، فلفل دلمه ای'}
['شات سس قارچ', 'سالاد کلم', 'ساندویچ چیکن دونر'] {'شات سس قارچ': 'دست ساز ، وزن 80 گرم', 'سالاد کلم': '100 گرم سالاد کلم', 'ساندویچ چیکن دونر': '120 گرم دونر مرغ، کلم قرمز، سس سیر، پیاز، جعفری، کاهو،  سس قارچ'}
['ته چین مرغ و بادمجان  سینه'] {'ته چین مرغ و بادمجان  سینه': '400 گرم ته چین مرغ شامل برنج ایرانی، 420 گرم سینه مرغ کامل به صورت جداگانه، بادمجان سرخ شده، با ظرف ماکروفری'}
['نوشابه خانواده کوکا کولا', 'پیتزا پپرونی'] {'نوشابه خانواده کوکا کولا': '1.5 لیتر', 'پیتزا پپرونی': 'خمیر پیتزا آمریکایی 25 سانتی متر، سس مخصوص پپرونی، پپرونی، قارج، پنیر مخصوص برگرلند\r\n'}
['آش رشته (ظرف بزرگ)'] {'آش رشته (ظرف بزرگ)': 'مناسب 2 نفر'}
['اسموکی چیز برگر', 'موزارلا چیز رول'] {'اسموکی چیز برگر': 'یک عدد برگر دست ساز گوشت گوساله 150 گرمی، پنیر دودی، پنیر چدار، کاهو فرانسوی، گوجه فرنگی، سس باربیکیو، سس مخصوص، سیب زمینی فرایز، نان گرد', 'موزارلا چیز رول': '5 عدد چیز رول، پنیر موزارلا، پنیر لبنه'}
['چلو خورشت قورمه سبزی'] {'چلو خورشت قورمه سبزی': 'یک پرس خورشت قورمه سبزی، 4 تکه گوشت گوساله، 350 گرم برنج ایرانی'}
['لیمو شیرین درجه 1 1 کیلوگرم ± 50 گرم', 'شلغم 500 گرم ± 25 گرم', 'پیاز سفید  1 کیلوگرم ± 50 گرم', 'هویج  1 کیلوگرم ± 50 گرم', 'سیب زمینی 1 کیلوگرم ± 50 گرم', 'لیمو ترش سنگی  500 گرم ± 25 گرم'] {'لیمو شیرین درجه 1 1 کیلوگرم ± 50 گرم': '', 'شلغم 500 گرم ± 25 گرم': '', 'پیاز سفید  1 کیلوگرم ± 50 گرم': '', 'هویج  1 کیلوگرم ± 50 گرم': '', 'سیب زمینی 1 کیلوگرم ± 50 گرم': 'غیر انباری ', 'لیمو ترش سنگی  500 گرم ± 25 گرم': ''}
['چلو خورشت فسنجان مرغ'] {'چلو خورشت فسنجان مرغ': '300 گرم خورشت فسنجان ملس، 2 تکه فیله مرغ، 400 گرم برنج ایرانی'}
['چلو ماهی قزل آلا کبابی'] {'چلو ماهی قزل آلا کبابی': '350 گرم ماهی قزل آلا کبابی، 350 گرم برنج ایرانی.همراه با دورچین'}
['سالاد فصل', 'چلو ساده', 'خوراک بره کباب'] {'سالاد فصل': 'کاهو، گوجه، خیار، هویج، سس سالاد', 'چلو ساده': '400 گرم برنج ایرانی', 'خوراک بره کباب': '300 گرم راسته تازه بره، پیاز، فلفل دلمه ای کبابی، گوجه، فلفل کبابی، دورچین روز'}
['چلو کباب وزیری', 'نوشابه بطری پپسی'] {'چلو کباب وزیری': 'یک سیخ جوجه کباب سینه مرغ 150 گرمی، یک سیخ کباب کوبیده گوشت مخلوط گوساله و گوسفندی 150 گرمی، گوجه کبابی، کره، لیمو', 'نوشابه بطری پپسی': '300 میلی لیتر'}
['نوشابه قوطی  کوکاکولا', 'نوشابه قوطی  زیرو', 'سالاد کلم', 'قارچ سوخاری', 'سالاد هاوایی (یک نفره)', 'راوا فینگر', 'پیتزا پنجره ای'] {'نوشابه قوطی  کوکاکولا': '330 میلی لیتر', 'نوشابه قوطی  زیرو': '330 میلی لیتر', 'سالاد کلم': 'کلم، هویج، جوانه گندم و سس مخصوص پرپروک', 'قارچ سوخاری': 'یک پرس قارچ سوخاری شده', 'سالاد هاوایی (یک نفره)': 'کاهو، بیبی اسفناج، آناناس، مغز بادام درختی، سس مخصوص پرتقال', 'راوا فینگر': '340گرم راوا فینگر (سیب زمینی سوخاری) به همراه  2عدد سس کچاپ مخصوص پرپروک ساشه و یک عدد سس کچاپ تند پرپروک ساشه\r\n', 'پیتزا پنجره ای': 'ژامبون گوشت، سوسیس، قارچ، فلفل دلمه ای، سس و پنیر مخصوص پرپروک '}
['کامل', 'ران مرغ 1 کیلوگرم', 'بدون پوست'] {'کامل': 'وزن ضایعات در هر کیلوگرم بین 150 تا 250 گرم،\r\nمناسب بریان، گریل، سوخاری یا پخت به صورت سس پز،\r\nارایه به صورت خرد شده، به صورت با استخوان یا بدون استخوان به درخواست شما در بسته بندی بهداشتی', 'ران مرغ 1 کیلوگرم': 'مناسب گریل، سوخاری یا پخت به صورت سس پز،\r\nارایه به صورت خرد شده و به صورت با استخوان یا بدون استخوان به درخواست شما در بسته بندی بهداشتی', 'بدون پوست': 'مناسب گریل، سوخاری یا پخت به صورت سس پز، ارایه به صورت خرد شده و به صورت با استخوان یا بدون استخوان به درخواست شما در بسته بندی بهداشتی'}
['ساندویچ هات داگ  ساده', 'سیب زمینی سرخ شده', 'نوشابه قوطی اسپرایت'] {'ساندویچ هات داگ  ساده': 'یک عدد سوسیس هات داگ 90%، کاهو، گوجه فرنگی، خیارشور، سس مخصوص، نان باگت', 'سیب زمینی سرخ شده': '300 گرم سیب زمینی سرخ شده', 'نوشابه قوطی اسپرایت': '330 میلی لیتر'}
['ساندویچ ژامبون لیونر سردویچ دو نفره'] {'ساندویچ ژامبون لیونر سردویچ دو نفره': '270 گرم ژامبون لیونر 60% گوشت، چیپس خلالی، سس ویژه، کاهو، خیارشور، گوجه فرنگی، نان باگت'}
['ساندویچ مخصوص کوکتل آرژانتینی کوچک'] {'ساندویچ مخصوص کوکتل آرژانتینی کوچک': 'کوکتل بخارپز ممتاز میکاییلیان، پنیر، چیپس، پیاز و جعفری، گوجه، خیارشور، سس مخصوص باماهاس، نان باگت'}
['آلوچه ریز 500 گرم', 'مغز گردو ایرانی معمولی 250 گرم', 'برگ قیصی 250 گرم', 'آلو بخارا 250 گرم', 'تمر هندی مارک کشتی اصل', 'مغر بادام شور ایرانی 250 گرم'] {'آلوچه ریز 500 گرم': 'بدون مواد و ملس', 'مغز گردو ایرانی معمولی 250 گرم': 'گردو خورشتی', 'برگ قیصی 250 گرم': '', 'آلو بخارا 250 گرم': '', 'تمر هندی مارک کشتی اصل': 'یک بسته 300 گرمی، ترش و ملس و کم نمک', 'مغر بادام شور ایرانی 250 گرم': ''}
['باقالی پلو با گوشت'] {'باقالی پلو با گوشت': '350 گرم شوید باقالی با برنج ایرانی، 150 گرم گوشت گوسفندی'}
['نوشابه بطری فانتا پرتقالی', 'کباب کوبیده یک سیخ'] {'نوشابه بطری فانتا پرتقالی': '300 میلی لیتر', 'کباب کوبیده یک سیخ': 'کباب کوبیده گوشت مخلوط گوساله و گوسفندی 100 گرمی، بدون دورچین، بدون نان'}
['نوشابه خانواده کوکا کولا', 'سالاد کلم', 'استرامبولی هات داگ'] {'نوشابه خانواده کوکا کولا': '1.5 لیتر', 'سالاد کلم': 'کلم سفید، هویج رنده شده، سس مخصوص، ادویه مخصوص (یک نفره)', 'استرامبولی هات داگ': 'سس آلفردو، دو عدد عدد هات داگ گوشت، پنیر میکس شده، خمیر مخصوص استرامبولی، یک نفره'}
['پیتزا میکس رویال', 'سیب زمینی سرخ کرده'] {'پیتزا میکس رویال': 'خمیر پیتزا ایتالیایی32 سانتی متری سس گوجه فرنگی، پنیر پیتزا، ژامبون مرغ 80درصد ، هات داگ 80درصد ، قارچ، زیتون، فلفل دلمه رنگی، گوجه گیلاسی', 'سیب زمینی سرخ کرده': '300 گرم سیب زمینی سرخ شده همراه با  ادویه مخصوص'}

In [ ]:
samples = samples[['comment_text', 'order', 'ingredients', "foods", "services", "qualities"]]
samples

,comment_text,order,ingredients,foods,services,qualities
0,افتضاح تا بحال به عمرم پیتزا به این بدی ندیده ...,['پیتزا سیر و استیک ایتالیایی یک نفره (25 سانت...,{'پیتزا سیر و استیک ایتالیایی یک نفره (25 سانت...,"{""{\""product_id\"": 22922785, \""product_title\""...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""food_rate\"": \""0\"", \""food_title\"": \""پیت..."
1,اصلا طعم قرمه سبزی نداشت یعنی اگر خودم سفارش ن...,"['چلو خورشت قورمه سبزی', 'نوشابه شیشه ای کوکا ...",{'چلو خورشت قورمه سبزی': '200 گرم خورشت٬ 70 گر...,"{""{\""product_id\"": 6391220, \""product_title\"":...",{},"{""{\""food_rate\"": \""1\"", \""food_title\"": \""چلو..."
2,چلوکباب سماغ نداشت,['چلو کباب\u200c کوبیده مخصوص اقتصادی'],{'چلو کباب\u200c کوبیده مخصوص اقتصادی': 'یک سی...,"{""{\""product_id\"": 23638165, \""product_title\""...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""food_rate\"": \""0\"", \""food_title\"": \""چلو..."
3,حتما دوبار سفارش می دم,['زرشک پلو با مرغ سس پز ران'],{'زرشک پلو با مرغ سس پز ران': 'یک تکه مرغ سس پ...,"{""{\""product_id\"": 5545444, \""product_title\"":...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""ز..."
4,عالی,['خوراک جوجه کباب ترش گیلانه'],{'خوراک جوجه کباب ترش گیلانه': 'یک سیخ جوجه کب...,"{""{\""product_id\"": 20430113, \""product_title\""...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""food_rate\"": \""5\"", \""food_title\"": \""خور..."
...,...,...,...,...,...,...
95,طعم برگر بشدت بد و بی مزه بود سیب زمینی های مخ...,"['همبرگر معمولی', 'ساندویچ هندی', 'نوشابه خانو...",{'همبرگر معمولی': 'برگر شرکتی 30%، کاهو، گوجه،...,"{""{\""product_id\"": 6256725, \""product_title\"":...","{""{\""service_rate\"": \""0\"", \""part_of_comment\...","{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""ن..."
96,فلفل کبابی نداشت و نونش کم بود نسبت به ۴ سیخی ...,['خوراک کباب کوبیده یک سیخ'],{'خوراک کباب کوبیده یک سیخ': 'کباب کوبیده گوشت...,"{""{\""product_id\"": 21436811, \""product_title\""...","{""{\""service_rate\"": \""2\"", \""part_of_comment\...","{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""خ..."
97,حجم مواد خوب بود و مزه خوبی داشت نسبتا ولی پیت...,"['س️اندویچ ژامبون تنوری مخصوص ویولا', 'پیتزا ک...",{'س️اندویچ ژامبون تنوری مخصوص ویولا': '200 گرم...,"{""{\""product_id\"": 24755883, \""product_title\""...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""س..."
98,عالی,['چلو خورشت قورمه سبزی'],{'چلو خورشت قورمه سبزی': 'یک پرس خورشت قورمه س...,"{""{\""product_id\"": 7588082, \""product_title\"":...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""food_rate\"": \""5\"", \""food_title\"": \""چلو..."
99,پول پیک پانزده هزار تومن نمیرزه,['ساندویچ هات بیتس'],{'ساندویچ هات بیتس': '2 عدد ساندویچ مینی ھات د...,"{""{\""product_id\"": 19131318, \""product_title\""...","{""{\""service_rate\"": \""1\"", \""part_of_comment\...","{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""س..."

In [ ]:
samples.to_csv("./samples.csv")

In [ ]:
samples.iloc[0]["ingredients"]

"{'پیتزا سیر و استیک ایتالیایی یک نفره (25 سانتی متری)': 'خمیر پیتزا ایتالیایی، استیک دست ساز گوشت گوساله، پنیر پیتزا، قارچ، زیتون سیاه، پیاز، سیر، فلفل دلمه ای، کره طعم دار'}"

In [ ]:
samples = df.sample(n=100)
samples = samples.reset_index(drop=True)
samples

,comment_text,qualities,services,foods
0,افتضاح تا بحال به عمرم پیتزا به این بدی ندیده ...,"{""{\""food_rate\"": \""0\"", \""food_title\"": \""پیت...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""product_id\"": 22922785, \""product_title\""..."
1,اصلا طعم قرمه سبزی نداشت یعنی اگر خودم سفارش ن...,"{""{\""food_rate\"": \""1\"", \""food_title\"": \""چلو...",{},"{""{\""product_id\"": 6391220, \""product_title\"":..."
2,چلوکباب سماغ نداشت,"{""{\""food_rate\"": \""0\"", \""food_title\"": \""چلو...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""product_id\"": 23638165, \""product_title\""..."
3,حتما دوبار سفارش می دم,"{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""ز...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""product_id\"": 5545444, \""product_title\"":..."
4,عالی,"{""{\""food_rate\"": \""5\"", \""food_title\"": \""خور...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""product_id\"": 20430113, \""product_title\""..."
...,...,...,...,...
95,طعم برگر بشدت بد و بی مزه بود سیب زمینی های مخ...,"{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""ن...","{""{\""service_rate\"": \""0\"", \""part_of_comment\...","{""{\""product_id\"": 6256725, \""product_title\"":..."
96,فلفل کبابی نداشت و نونش کم بود نسبت به ۴ سیخی ...,"{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""خ...","{""{\""service_rate\"": \""2\"", \""part_of_comment\...","{""{\""product_id\"": 21436811, \""product_title\""..."
97,حجم مواد خوب بود و مزه خوبی داشت نسبتا ولی پیت...,"{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""س...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""product_id\"": 24755883, \""product_title\""..."
98,عالی,"{""{\""food_rate\"": \""5\"", \""food_title\"": \""چلو...","{""{\""service_rate\"": \""Nan\"", \""part_of_commen...","{""{\""product_id\"": 7588082, \""product_title\"":..."
99,پول پیک پانزده هزار تومن نمیرزه,"{""{\""food_rate\"": \""Nan\"", \""food_title\"": \""س...","{""{\""service_rate\"": \""1\"", \""part_of_comment\...","{""{\""product_id\"": 19131318, \""product_title\""..."

In [ ]:
prompt_enhancements = """Suppose that we are working in the domain of a food delivery app.
Here is the list of foods and beverages ordered by a user, let's call it 'UserOrder':
UserOrder: {order}

After receiving the 'UserOrder', here is the user's comment (review) about their experience having UserOrder (called 'UserComment'):
UserComment: {comment}
As you see, UserComment expresses the user's satisfaction with the food quality and services delivered.

Having the context provided, your task is to evaluate the food quality and services delivered based on UserComment. In other words, you should assign a score per each food and services delivered. Let's think step by step:
First, inspect the UserComment precisely.

Then, Based on UserComment, assign a score per each of the foods ordered (an integer between 0 and 5). In other words, all the food titles mentioned in the UserOrder must get a score field. If UserComment does not include any specific review for any of the food ordered, set the corresponding food score to 'Nan'.
*ATTENTION*: In this step, if UserComment is a general positive or negative comment and does not specify any particular food item, apply it to all food items ordered.
For example: Having UserComment='همه چی عالی', all the food items ordered will get a 5 score.

For the next step, refer to UserComment again. Based on UserComment, assign a score per each service provided (if any). To achieve this, first, you need to specify the relevant part of the UserComment expressing the user's experience with the service. Then, classify that service into one of these categories:
'[Delivery time, Quality of packaging, Cost of packaging, Cost per value of foods, Overall quality, Staff behavior, Food temperature, Delivered food not as ordered]'
After that, assign a score (an integer between 0 and 5) to that service based on part_of_comment. Feel free to set the service score as 'Nan' if the user seems unclear about the satisfaction with the service provided.

*ATTENTION*: As you see, the UserComment is in Persian. Thus, be mindful of any different Persian idioms or slang used and their actual meanings.

Finally, Based on the information inferred in the previous steps, generate JSON about the foods and services in this format:
```
 {{
    qualities: [
        {{
            food_title: <food_title>,
            food_rate: <food_rate>
        }}
    ],
    services: [
        {{
            part_of_comment: '<part_of_comment>',
            service_rate: '<service_rate>',
            service_classified: '<service_classified>'
        }}
    ]
}}
```
Output only the JSON. Do not output any extra information or explanations.
"""

system_role = "You are a helpful digital assisstant having brilliant analytical skills."

In [ ]:
with open('./output.txt', 'w', encoding='utf-8') as f:
    for index, row in samples.iterrows():

        prompt = prompt_enhancements.format(order=row['foods'], comment=row['comment_text'])
        messages = [{"role": "system",
                "content": f"{system_role}"},
    {"role": "user",
    "content": f"{prompt}"}]


    inputs = tokenizer.apply_chat_template(messages, add_generation_prompt=True, return_tensors="pt")

    outputs = model.generate(inputs, max_new_tokens=2000, temperature=0.0)
    text = tokenizer.batch_decode(outputs[:, inputs.shape[1]:])[0]
    answer = f"""comment {index}: {row['comment_text']} \n
    response: \n
    {text}
    \n
    """
    f.write(answer)
    print(f"{index} Done.")

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:500: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(

1 Done.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import json

In [ ]:
df.loc[3]

comment_text           کیفیت برگرا عالی ولی سیب زمینی خیلی معمولی
qualities       {"{\"food_rate\": \"Nan\", \"food_title\": \"ن...
services        {"{\"service_rate\": \"Nan\", \"part_of_commen...
foods           {"{\"product_id\": 18749778, \"product_title\"...
Name: 3, dtype: object

In [ ]:
test_case = """ UserOrder: '['نوشابه قوطی کوکا کولا', 'جوسی برگر', 'ساندویچ رست چیکن', 'سیب زمینی سرخ کرده']'
UserComment: 'کیفیت برگرا عالی ولی سیب زمینی خیلی معمولی'
"""
json_analytics = """
 "qualities": [
        {
            "food_title": "سیب زمینی سرخ کرده",
            "food_rate": "2"
        },
        {
            "food_title: ساندویچ رست چیکن",
            "food_rate": "Nan"
        },
        {
            "food_title": "جوسی برگر",
            "food_rate": "5"
        },
        {
            "food_title": "نوشابه قوطی کوکا کولا",
            "food_rate": "Nan"
        }
    ],
    "services": [
        {
        }
    ]
}
"""

In [ ]:
from transformers import pipeline

messages = [
    {"role": "user", "content": f"{test_case}"},
    {"role": "assistant", "content": f"{json_analytics}"},
    {"role": "user", "content": f"{prompt_enhancements}"},
]

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
)

generation_args = {
    "max_new_tokens": 2000,
    "return_full_text": False,
    "temperature": 0.0,
    "do_sample": False,
}

output = pipe(messages, **generation_args)
print(output[0]['generated_text'])

{
    "qualities": [
        {
            "food_title": "چلو کباب کوبیده مخصوص دو سیخ (110 گرمی)",
            "food_rate": "1"
        },
        {
            "food_title": "چلو کباب لقمه",
            "food_rate": "1"
        },
        {
            "food_title": "نوشابه بطری کوکا کولا",
            "food_rate": "Nan"
        },
        {
            "food_title": "سالاد فصل",
            "food_rate": "Nan"
        }
    ],
    "services": [
        {
            "part_of_comment": "سالادش خیلی تلخ و بد مزه بود",
            "service_rate": "Nan",
            "service_classified": "Overall quality"
        }
    ]
}